version: '3.8'

services:
  website:
    image: ghcr.io/drozdovas/drozdovas.com:latest
    container_name: drozdovas-website
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - web

networks:
  web:
    name: web